"""Canonical application constants."""

APP_NAME = "GitDock"
APP_SLUG = "gitdock"
PRIMARY_UI_LANGUAGE = "ar"
TELEGRAM_CALLBACK_PREFIX = "gd"
CALLBACK_SCHEMA_VERSION = "v1"

HEALTH_PATH = "/health"
READINESS_PATH = "/ready"
TELEGRAM_WEBHOOK_PATH = "/telegram/webhook"
GITHUB_SETUP_CALLBACK_PATH = "/github/setup/callback"
GITHUB_OAUTH_CALLBACK_PATH = "/github/oauth/callback"

GITHUB_API_BASE_URL = "https://api.github.com"
GITHUB_WEB_BASE_URL = "https://github.com"
GITHUB_OAUTH_AUTHORIZE_URL = "https://github.com/login/oauth/authorize"
GITHUB_OAUTH_ACCESS_TOKEN_URL = "https://github.com/login/oauth/access_token"
GITHUB_REST_API_VERSION = "2026-03-10"
GITHUB_ACCEPT_HEADER = "application/vnd.github+json"
GITHUB_USER_AGENT = "GitDock/0.1"

GITHUB_APP_JWT_IAT_SKEW_SECONDS = 60
GITHUB_APP_JWT_LIFETIME_SECONDS = 9 * 60
INSTALLATION_TOKEN_REFRESH_MARGIN_SECONDS = 5 * 60
GITHUB_AUTH_STATE_TTL_SECONDS = 10 * 60

HTTP_CONNECT_TIMEOUT_SECONDS = 10.0
HTTP_READ_TIMEOUT_SECONDS = 30.0
GITHUB_MAX_RETRIES = 3
RETRY_BASE_DELAY_SECONDS = 0.5
RETRY_MAX_DELAY_SECONDS = 8.0
GITHUB_MAX_PAGES = 100
GITHUB_REPOSITORY_FETCH_PAGE_SIZE = 100

DEFAULT_PAGE_SIZE = 8
SEARCH_PAGE_SIZE = 6
SEARCH_QUERY_MAX_CHARS = 180
SEARCH_COMPILED_QUERY_MAX_CHARS = 240
SEARCH_SESSION_ID_BYTES = 6
SEARCH_OWNER_LOGIN_MAX_CHARS = 39
SEARCH_TOPIC_MAX_CHARS = 50
SEARCH_MIN_STARS_MAX = 1_000_000_000

NAV_HOME = "🏠 الرئيسية"
NAV_CANCEL = "❌ إلغاء"
NAV_BACK = "⬅️ رجوع"
NAV_REFRESH = "🔄 تحديث"
